openapi: 3.1.0
info:
  title: Miran Paper Webhook
  version: 1.1.0
servers:
  - url: https://miran-0uep.onrender.com
paths:
  /miran-hook:
    post:
      summary: Pubblica una conversazione approvata nel canale Telegram, con o senza immagine
      operationId: pubblicaConversazione
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                domanda:
                  type: string
                  description: La domanda o messaggio iniziale dell'utente
                risposta:
                  type: string
                  description: La risposta poetica generata da Miran
                timestamp:
                  type: string
                  description: Data e ora della pubblicazione
                immagine_url:
                  type: string
                  format: uri
                  description: (Opzionale) URL pubblico dell'immagine da pubblicare insieme alla risposta
              required:
                - domanda
                - risposta
                - timestamp
      responses:
        "200":
          description: Pubblicazione avvenuta con successo
