
services:
  - type: web
    name: miran-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python miran_combined_webhook.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: WEBHOOK_URL
        sync: false
    autoDeploy: true
